#!/usr/bin/env bash
# Deploy mail transport credentials to Node B for the go-choir-maild service.
#
# This reads RESEND_API_KEY and RESEND_WEBHOOK_SECRET from
# ${CHOIR_MAIL_ENV_FILE:-./.env} or the current environment, writes them to
# /var/lib/go-choir/maild.env, and restarts maild. The file is runtime-only
# host state; it is not committed to git or embedded in the Nix store.
#
# Usage:
#   ./nix/deploy-mail-creds.sh
#   ./nix/deploy-mail-creds.sh node-b
set -euo pipefail

HOST="${1:-node-b}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${CHOIR_MAIL_ENV_FILE:-${REPO_ROOT}/.env}"
REMOTE_ENV_FILE="/var/lib/go-choir/maild.env"

if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
else
  echo "warning: $ENV_FILE not found; relying on exported environment variables" >&2
fi

required=()
for key in RESEND_API_KEY RESEND_WEBHOOK_SECRET; do
  if [ -z "${!key:-}" ]; then
    required+=("$key")
  fi
done

if [ ${#required[@]} -gt 0 ]; then
  echo "error: missing required mail credential(s): ${required[*]}" >&2
  exit 1
fi

ENVS=(
  "RESEND_API_KEY=${RESEND_API_KEY}"
  "RESEND_WEBHOOK_SECRET=${RESEND_WEBHOOK_SECRET}"
)

for key in RESEND_BASE_URL MAILD_ROOT_OWNER_ID MAILD_PRIMARY_DOMAIN; do
  if [ -n "${!key:-}" ]; then
    ENVS+=("${key}=${!key}")
  fi
done

ENV_CONTENT=$(printf '%s\n' "${ENVS[@]}")
ENV_CONTENT="${ENV_CONTENT}
# Auto-generated by deploy-mail-creds.sh - DO NOT COMMIT
# Regenerate with: ./nix/deploy-mail-creds.sh"

echo "Deploying mail credentials to ${HOST}:${REMOTE_ENV_FILE}"

ssh "$HOST" "install -d -m 0750 /var/lib/go-choir/mail
cat > ${REMOTE_ENV_FILE}.tmp << 'MAIL_ENV_EOF'
${ENV_CONTENT}
MAIL_ENV_EOF
mv ${REMOTE_ENV_FILE}.tmp ${REMOTE_ENV_FILE}
chmod 600 ${REMOTE_ENV_FILE}
systemctl restart go-choir-maild
echo 'Mail credentials deployed and maild restarted.'
systemctl is-active go-choir-maild"

echo "Done."
