#!/usr/bin/env bash
# Deploy mail transport credentials to Node B for the go-choir-maild service.
#
# This reads RESEND_API_KEY and RESEND_WEBHOOK_SECRET from
# ${CHOIR_MAIL_ENV_FILE:-./.env}, an optional webhook secret file, or the current
# environment, writes them to /var/lib/go-choir/maild.env, and restarts maild.
# The file is runtime-only host state; it is not committed to git or embedded
# in the Nix store.
#
# Usage:
#   ./nix/deploy-mail-creds.sh
#   ./nix/deploy-mail-creds.sh node-b
#   CHOIR_MAIL_WEBHOOK_SECRET_FILE=/tmp/resend-webhook-secret.env ./nix/deploy-mail-creds.sh --dry-run
set -euo pipefail

HOST="node-b"
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage:
  nix/deploy-mail-creds.sh [host] [--dry-run]

Environment:
  CHOIR_MAIL_ENV_FILE             Optional base env file. Default: ./.env
  CHOIR_MAIL_WEBHOOK_SECRET_FILE  Optional file containing RESEND_WEBHOOK_SECRET=...
  RESEND_WEBHOOK_SECRET_FILE      Alias for CHOIR_MAIL_WEBHOOK_SECRET_FILE

The webhook secret file is intended to consume output from:
  scripts/mail-resend-setup --write-webhook-secret-file /tmp/resend-webhook-secret.env
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      HOST="$1"
      shift
      ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${CHOIR_MAIL_ENV_FILE:-${REPO_ROOT}/.env}"
WEBHOOK_SECRET_FILE="${CHOIR_MAIL_WEBHOOK_SECRET_FILE:-${RESEND_WEBHOOK_SECRET_FILE:-}}"
REMOTE_ENV_FILE="/var/lib/go-choir/maild.env"

if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
else
  echo "warning: $ENV_FILE not found; relying on exported environment variables" >&2
fi

if [ -n "$WEBHOOK_SECRET_FILE" ]; then
  if [ ! -f "$WEBHOOK_SECRET_FILE" ]; then
    echo "error: webhook secret file not found: $WEBHOOK_SECRET_FILE" >&2
    exit 1
  fi
  set -a
  # shellcheck disable=SC1090
  source "$WEBHOOK_SECRET_FILE"
  set +a
fi

required=()
for key in RESEND_API_KEY RESEND_WEBHOOK_SECRET; do
  if [ -z "${!key:-}" ]; then
    required+=("$key")
  fi
done

if [ ${#required[@]} -gt 0 ]; then
  echo "error: missing required mail credential(s): ${required[*]}" >&2
  exit 1
fi

ENVS=(
  "RESEND_API_KEY=${RESEND_API_KEY}"
  "RESEND_WEBHOOK_SECRET=${RESEND_WEBHOOK_SECRET}"
)

for key in RESEND_BASE_URL MAILD_ROOT_OWNER_ID MAILD_PRIMARY_DOMAIN; do
  if [ -n "${!key:-}" ]; then
    ENVS+=("${key}=${!key}")
  fi
done

ENV_CONTENT=$(printf '%s\n' "${ENVS[@]}")
ENV_CONTENT="${ENV_CONTENT}
# Auto-generated by deploy-mail-creds.sh - DO NOT COMMIT
# Regenerate with: ./nix/deploy-mail-creds.sh"

if [ "$DRY_RUN" -eq 1 ]; then
  echo "Mail credential deploy dry-run."
  echo "target: ${HOST}:${REMOTE_ENV_FILE}"
  echo "base_env_file: ${ENV_FILE}"
  if [ -n "$WEBHOOK_SECRET_FILE" ]; then
    echo "webhook_secret_file: ${WEBHOOK_SECRET_FILE}"
  else
    echo "webhook_secret_file: <not used>"
  fi
  echo "configured_keys:"
  printf '  - RESEND_API_KEY\n'
  printf '  - RESEND_WEBHOOK_SECRET\n'
  for key in RESEND_BASE_URL MAILD_ROOT_OWNER_ID MAILD_PRIMARY_DOMAIN; do
    if [ -n "${!key:-}" ]; then
      printf '  - %s\n' "$key"
    fi
  done
  echo "No remote files changed and maild was not restarted."
  exit 0
fi

echo "Deploying mail credentials to ${HOST}:${REMOTE_ENV_FILE}"

ssh "$HOST" "install -d -m 0750 /var/lib/go-choir/mail
cat > ${REMOTE_ENV_FILE}.tmp << 'MAIL_ENV_EOF'
${ENV_CONTENT}
MAIL_ENV_EOF
mv ${REMOTE_ENV_FILE}.tmp ${REMOTE_ENV_FILE}
chmod 600 ${REMOTE_ENV_FILE}
systemctl restart go-choir-maild
echo 'Mail credentials deployed and maild restarted.'
systemctl is-active go-choir-maild"

echo "Done."
