// Generated by frontend/scripts/generate-source-contract.mjs. Do not edit by hand.
// source-contract-schema-sha256: a0ccd582fabefc4ad695d22d3545d2e94393ad876868a001beb2d963471e1c43

export const SOURCE_CONTRACT_SCHEMA = {
  "evidence_states": {
    "candidate": {
      "aliases": [
        "pending",
        "needs_source",
        "source_needed"
      ],
      "label": "Candidate source",
      "relational": false
    },
    "available": {
      "aliases": [],
      "label": "Available source",
      "relational": false
    },
    "confirms": {
      "aliases": [
        "confirming",
        "confirmed",
        "represented",
        "owner_supplied"
      ],
      "label": "Confirms claim",
      "relational": true
    },
    "refutes": {
      "aliases": [
        "refuting",
        "refuted"
      ],
      "label": "Refutes claim",
      "relational": true
    },
    "qualifies": {
      "aliases": [
        "qualifying",
        "qualified"
      ],
      "label": "Qualifies claim",
      "relational": true
    },
    "no_source_needed": {
      "aliases": [
        "not_needed",
        "no_source"
      ],
      "label": "No source needed",
      "relational": false
    },
    "stale": {
      "aliases": [],
      "label": "Stale source",
      "relational": false
    },
    "blocked_by_access": {
      "aliases": [
        "blocked",
        "blocked_access",
        "access_blocked"
      ],
      "label": "Blocked by access",
      "relational": false
    },
    "unavailable": {
      "aliases": [
        "error",
        "failed",
        "fetch_failed"
      ],
      "label": "Unavailable source",
      "relational": false
    }
  },
  "reader_artifact_states": {
    "reader_snapshot_ready": {
      "aliases": [
        "ready",
        "snapshot_ready"
      ],
      "label": "Reader snapshot ready"
    },
    "not_publication_safe": {
      "aliases": [
        "publication_blocked",
        "not_safe_for_publication"
      ],
      "label": "Not publication safe"
    },
    "bounded_excerpt_only": {
      "aliases": [
        "excerpt_only",
        "bounded_excerpt"
      ],
      "label": "Bounded excerpt only"
    },
    "import_failed": {
      "aliases": [
        "failed",
        "fetch_failed",
        "source_import_failed"
      ],
      "label": "Source import failed"
    }
  },
  "selector_kinds": {
    "whole_resource": {
      "aliases": [
        "",
        "whole",
        "resource",
        "whole_document",
        "whole_source"
      ]
    },
    "text_quote": {
      "aliases": [
        "quote",
        "quoted_text"
      ]
    },
    "text_position": {
      "aliases": [
        "text_range",
        "char_range",
        "character_range"
      ]
    },
    "paragraph_heading": {
      "aliases": [
        "paragraph",
        "heading",
        "heading_range",
        "paragraph_range"
      ]
    },
    "byte_range": {
      "aliases": [
        "bytes"
      ]
    },
    "page_range": {
      "aliases": [
        "pages"
      ]
    },
    "timestamp_range": {
      "aliases": [
        "timestamp",
        "time_range",
        "media_range"
      ]
    },
    "transcript_segment": {
      "aliases": [
        "transcript",
        "segment",
        "transcript_segments"
      ]
    },
    "table_range": {
      "aliases": [
        "table",
        "table_rows",
        "row_range"
      ]
    },
    "table_cell": {
      "aliases": [
        "cell",
        "table_cells"
      ]
    },
    "image_region": {
      "aliases": [
        "region",
        "image_selector",
        "image_area"
      ]
    },
    "data_vintage": {
      "aliases": [
        "vintage",
        "data_release_vintage"
      ]
    },
    "selector_set": {
      "aliases": [
        "selectors"
      ]
    }
  },
  "open_surfaces": {
    "source": {
      "aliases": [
        "source_viewer",
        "source_reader",
        "reader",
        "content"
      ]
    },
    "web_lens": {
      "aliases": [
        "weblens",
        "browser",
        "web",
        "live",
        "original",
        "live_original"
      ]
    },
    "texture": {
      "aliases": [
        "texture",
        "published_texture",
        "published_texture_span",
        "published_texture",
        "publication_version",
        "published_texture_span"
      ]
    },
    "video": {
      "aliases": [
        "youtube",
        "youtube_video"
      ]
    },
    "image": {
      "aliases": []
    },
    "audio": {
      "aliases": [
        "podcast"
      ]
    },
    "pdf": {
      "aliases": [
        "document_pdf"
      ]
    },
    "transcript": {
      "aliases": [
        "captions"
      ]
    },
    "file": {
      "aliases": [
        "file_artifact",
        "attachment"
      ]
    },
    "source_window": {
      "aliases": [
        "source_panel",
        "source_popover"
      ]
    }
  }
} as const;

export const SOURCE_EVIDENCE_STATES = {
  "candidate": "candidate",
  "available": "available",
  "confirms": "confirms",
  "refutes": "refutes",
  "qualifies": "qualifies",
  "noSourceNeeded": "no_source_needed",
  "stale": "stale",
  "blockedByAccess": "blocked_by_access",
  "unavailable": "unavailable"
} as const;

export const SOURCE_OPEN_SURFACES = {
  "source": "source",
  "webLens": "web_lens",
  "texture": "texture",
  "video": "video",
  "image": "image",
  "audio": "audio",
  "pdf": "pdf",
  "transcript": "transcript",
  "file": "file",
  "sourceWindow": "source_window"
} as const;

export const READER_ARTIFACT_STATES = {
  "ready": "reader_snapshot_ready",
  "notPublicationSafe": "not_publication_safe",
  "boundedExcerptOnly": "bounded_excerpt_only",
  "importFailed": "import_failed"
} as const;

export const SOURCE_SELECTOR_KINDS = {
  "wholeResource": "whole_resource",
  "textQuote": "text_quote",
  "textPosition": "text_position",
  "paragraphHeading": "paragraph_heading",
  "byteRange": "byte_range",
  "pageRange": "page_range",
  "timestampRange": "timestamp_range",
  "transcriptSegment": "transcript_segment",
  "tableRange": "table_range",
  "tableCell": "table_cell",
  "imageRegion": "image_region",
  "dataVintage": "data_vintage",
  "selectorSet": "selector_set"
} as const;
